import { pgTable, text, serial, timestamp, integer, boolean } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

/**
 * @table chat_sessions
 *
 * Stores AI concierge chat sessions for the AURELION platform.
 * Each session represents a single conversation thread between a user and the
 * AI travel concierge, optionally scoped to a specific itinerary.
 *
 * **Business context:**
 * The AI concierge is a **Premium-tier-only** feature ($49.99). It provides
 * personalized Aruba travel advice, activity recommendations, and itinerary
 * optimization. In production, it uses OpenAI `gpt-4o-mini`; when the
 * `OPENAI_API_KEY` environment variable is not set, the system returns mock
 * responses for development and testing.
 *
 * **Relationships:**
 * - Belongs to `users` via `user_id` (no FK constraint; enforced in app code).
 * - Optionally scoped to `itineraries` via `itinerary_id` — when set, the AI
 *   has context about the user's trip plan and can give targeted suggestions.
 * - Has many `chat_messages` via `chat_messages.session_id`.
 *
 * **Indexing notes:**
 * - Primary key on `id`.
 * - Consider adding an index on `user_id` for the "my conversations" list.
 */
export const chatSessionsTable = pgTable("chat_sessions", {
  /** @param id — Auto-incrementing primary key. Referenced by `chat_messages.session_id`. */
  id: serial("id").primaryKey(),

  /**
   * @param userId — Soft foreign key to `users.id`.
   * Identifies the user who owns this chat session. Always required.
   * The API enforces that only Premium-tier users (or admins) can create sessions.
   */
  userId: integer("user_id").notNull(),

  /**
   * @param itineraryId — Soft foreign key to `itineraries.id`.
   * When set, the AI concierge loads the itinerary's activities and schedule
   * into its system prompt, enabling context-aware recommendations like
   * "Your Day 2 afternoon is free — consider adding snorkeling at Mangel Halto."
   * Nullable — null means a general Aruba travel chat not tied to a trip.
   */
  itineraryId: integer("itinerary_id"),

  /**
   * @param createdAt — Timestamp (with timezone) of when the session was started.
   * Defaults to `now()` at insert time. Used for ordering in the session list.
   */
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),

  /**
   * @param compressedHistory — AI-generated summary of archived conversation turns.
   * Old turns (all except last 5) are compressed into this summary to keep
   * the context window small while preserving conversational continuity.
   */
  compressedHistory: text("compressed_history"),

  /** @param lastCompressedAt — When compression was last run on this session. */
  lastCompressedAt: timestamp("last_compressed_at", { withTimezone: true }),

  /** @param compressionCount — How many times this session has been compressed. */
  compressionCount: integer("compression_count").notNull().default(0),
});

/**
 * @table chat_messages
 *
 * Stores individual messages within a chat session, forming the conversation
 * history between the user and the AI concierge.
 *
 * **Business context:**
 * Messages are ordered by `createdAt` to reconstruct the conversation timeline.
 * The full message history for a session is sent to the OpenAI API on each
 * user message to maintain conversational context. Messages are never edited
 * or deleted — the conversation is append-only.
 *
 * **Relationships:**
 * - Belongs to `chat_sessions` via `session_id` (no FK constraint).
 *
 * **Indexing notes:**
 * - Primary key on `id`.
 * - Consider adding an index on `(session_id, created_at)` for efficient
 *   conversation-history retrieval ordered by time.
 */
export const chatMessagesTable = pgTable("chat_messages", {
  /** @param id — Auto-incrementing primary key. */
  id: serial("id").primaryKey(),

  /**
   * @param sessionId — Soft foreign key to `chat_sessions.id`.
   * Links this message to its parent conversation. Always required.
   */
  sessionId: integer("session_id").notNull(),

  /**
   * @param role — Identifies who sent this message in the conversation.
   * Valid values: `"user"` | `"assistant"`.
   * - `"user"` — message typed by the human user.
   * - `"assistant"` — response generated by the AI concierge (gpt-4o-mini
   *   in production, or a mock response when OPENAI_API_KEY is not set).
   * These values align with the OpenAI Chat Completions API `role` field,
   * so the message history can be passed directly to the API.
   */
  role: text("role").notNull(),

  /**
   * @param content — The full text content of the message.
   * For user messages: the raw text the user typed.
   * For assistant messages: the AI-generated response, which may contain
   * markdown formatting (rendered in the chat UI).
   */
  content: text("content").notNull(),

  /**
   * @param isArchived — TRUE when this message has been compressed into the
   * session's `compressedHistory` summary. Archived messages are excluded
   * from the active context window sent to OpenAI.
   */
  isArchived: boolean("is_archived").notNull().default(false),

  /**
   * @param tokenCount — Approximate token count for this message.
   * Used to decide when compression is needed (e.g., total > 4000 tokens).
   */
  tokenCount: integer("token_count"),

  /**
   * @param createdAt — Timestamp (with timezone) of when this message was sent.
   * Defaults to `now()` at insert time. Messages within a session are
   * ordered by this field to reconstruct the conversation timeline.
   */
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

/**
 * Zod schema for inserting a new chat session row.
 * Omits `id` (auto-generated) and `createdAt` (server-default).
 * Used when a Premium user initiates a new concierge conversation.
 *
 * @example
 * ```ts
 * const session = insertChatSessionSchema.parse({
 *   userId: user.id,
 *   itineraryId: itinerary?.id ?? null,
 * });
 * const [row] = await db.insert(chatSessionsTable).values(session).returning();
 * ```
 */
export const insertChatSessionSchema = createInsertSchema(chatSessionsTable).omit({
  id: true,
  createdAt: true,
});

/**
 * Zod schema for inserting a new chat message row.
 * Omits `id` (auto-generated) and `createdAt` (server-default).
 * Used when appending a user or assistant message to a session.
 *
 * @example
 * ```ts
 * const msg = insertChatMessageSchema.parse({
 *   sessionId: session.id,
 *   role: "user",
 *   content: "What's the best time to visit the Natural Pool?",
 * });
 * await db.insert(chatMessagesTable).values(msg);
 * ```
 */
export const insertChatMessageSchema = createInsertSchema(chatMessagesTable).omit({
  id: true,
  createdAt: true,
});

/** TypeScript type for a validated chat-session insert payload. */
export type InsertChatSession = z.infer<typeof insertChatSessionSchema>;

/** TypeScript type for a full chat-session row as returned by a `SELECT *` query. */
export type ChatSession = typeof chatSessionsTable.$inferSelect;

/** TypeScript type for a validated chat-message insert payload. */
export type InsertChatMessage = z.infer<typeof insertChatMessageSchema>;

/** TypeScript type for a full chat-message row as returned by a `SELECT *` query. */
export type ChatMessage = typeof chatMessagesTable.$inferSelect;
